### ISSUE TITLE
`PilImageGenerator` incompatible with pillow >= 10, `AttributeError: 'ImageDraw' object has no attribute 'textsize'`

### ISSUE THREAD

**Issue by perrinjerome** [barseghyanartur/faker-file#77]
```console
$ pip install faker-file pillow
```

```console
$ pip freeze
Faker==30.8.1
faker-file==0.17.12
pillow==11.0.0
python-dateutil==2.9.0.post0
six==1.16.0
typing_extensions==4.12.2
```

run the example from https://github.com/barseghyanartur/faker-file/blob/00a0b388fd8fabf01ca819e92a5aa5c19710787e/docs/_static/examples/creating_images/pillow_1.py

```pytb

Traceback (most recent call last):
  File "./pillow_1.py", line 8, in <module>
    png_file = FAKER.png_file(image_generator_cls=PilImageGenerator)
  File "./lib/python3.9/site-packages/faker_file/providers/png_file.py", line 157, in png_file
    return self._image_file(
  File "./lib/python3.9/site-packages/faker_file/providers/mixins/image_mixin.py", line 163, in _image_file
    _raw_content = image_generator.generate(
  File "./lib/python3.9/site-packages/faker_file/providers/image/pil_generator.py", line 275, in generate
    line_max_num_chars = self.find_max_fit_for_multi_line_text(
  File "./lib/python3.9/site-packages/faker_file/providers/image/pil_generator.py", line 168, in find_max_fit_for_multi_line_text
    return cls.find_max_fit_for_single_line_text(
  File "./lib/python3.9/site-packages/faker_file/providers/image/pil_generator.py", line 183, in find_max_fit_for_single_line_text
    text_width, _ = draw.textsize(text[:mid], font=font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

https://pillow.readthedocs.io/en/stable/deprecations.html#font-size-and-offset-methods explains how to update to the new API.

**Comment by barseghyanartur** [comment]
Fixed in 0.17.13.
